#to do: git config --global user.name "John Doe"
#to do: git config --global user.email johndoe@example.com

---
- hosts: workstation
  roles:
    - {role: common, become: true}
    - {role: java8, become: true}
    - {role: spotify, become: true}
    - {role: google-chrome, become: true}

  tasks:

  - name: Add Virtualbox repository keys
    become: yes
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

  - name: Add Virtualbox repository
    become: yes
    apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

  - name: Install VirtualBox
    become: yes
    apt: pkg=virtualbox-5.1 state=present allow-unauthenticated=yes

