#to do: git config --global user.name "John Doe"
#to do: git config --global user.email johndoe@example.com

---
- hosts: workstation
  roles:
    - {role: common, become: true}
    - {role: java8, become: true}
    - {role: spotify, become: true}
    - {role: google-chrome, become: true}
    - {role: virtualbox, become: true}

