#to do: git config --global user.name "John Doe"
#to do: git config --global user.email johndoe@example.com

---
- hosts: workstation
  tasks: 
  - name: install common packages
    become: true
    apt: name={{ item }} state=present
    with_items:
    - python-selinux
    - git
    - docker
    - docker-compose
    - network-manager-openconnect
    - software-properties-common
    - gnome-shell
    - gnome-tweak-tool
    - vlc
    - firewalld
  
  - name: add user to the docker group
    become: true    
    user: name=bufoor groups=docker append=yes

  - name: Add Oracle Java Repository
    become: true
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: true
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
     - oracle-java8-installer
     - ca-certificates
     - oracle-java8-set-default

  - name: Add Spotify repository
    become: yes
    apt_repository: repo='deb http://repository.spotify.com stable non-free'
  
  - name: Add Spotify repository keys
    become: yes
    apt_key: keyserver=keyserver.ubuntu.com id=94558F59

  - name: Install Spotify client
    become: yes
    apt: name=spotify-client state=present allow-unauthenticated=yes
    
  - name: Add Google Chrome repository keys
    become: yes
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

  - name: Add Google Chrome repository
    become: yes
    copy:
     content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
     dest: "/etc/apt/sources.list.d/google-chrome.list"

  - name: Install Google Chrome Stable
    become: yes
    apt: name=google-chrome-stable update_cache=yes

  - name: Add Virtualbox repository keys
    become: yes
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

  - name: Add Virtualbox repository
    become: yes
    apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

  - name: Install VirtualBox
    become: yes
    apt: pkg=virtualbox-5.1 state=present allow-unauthenticated=yes

