---
- name: Install
  apt: name=git state=present

- name: Add global username
  git_config: name=user.name value="{{user_name}}" scope=system

- name: Add global user email
  git_config: name=user.email value="{{user_email}}" scope=system

