---
- name: Add git lfs repository
  shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

- name: Install
  apt: name=git state=present

- name: Install LFS
  apt: name=git-lfs state=present

- name: Add global username
  git_config: name=user.name value="{{user_name}}" scope=system

- name: Add global user email
  git_config: name=user.email value="{{user_email}}" scope=system
