---
- name: Add Virtualbox repository keys
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: Add Virtualbox repository
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

- name: Install
  apt: pkg=virtualbox-5.1 state=present allow-unauthenticated=yes

