---
- name: Install
  apt: name="{{ item }}" state=present
  with_items:
   - docker
   - docker-compose

- name: Add user to the docker group
  user: name=bufoor groups=docker append=yes

- name: Restart deamon
  service: name=docker state=restarted

